name: autofix.ci

on:
  push:
  pull_request:

jobs:
  autofix:
    name: Auto Fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cargo Format
        uses: yonasBSD/toolkit@cdcd732fe7504e00e89a48ce83ac40467799d8df # v0.1.0
        with:
          run: |
            cargo format

      - name: Autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          commit-message: "fix(ci): [autofix.ci] apply automated fixes"
